import type { CodexEntry } from './Codex';

// The manual: how to play, as opposed to how the universe ends. Plain instructions, in the
// order a new player needs them.

export const MANUAL: CodexEntry[] = [
  {
    id: 'm-start',
    title: 'Getting started',
    body: [
      'Your people live on Aster, a tidally locked world around a red dwarf that is running down. Its core is cooling and its air is being stripped away. The goal is simple to say: keep your people alive for as long as the universe allows, and decide what alive means.',
      'Your first turns: choose a research project (the first button on the left rail). Click Aster and queue something to build. Send your two survey probes to nearby stars. Then press End Turn, or Enter.',
      'Every button explains itself if you hover over it. The chips above End Turn list anything still waiting for you; click one to go there.',
    ],
  },
  {
    id: 'm-time',
    title: 'Turns, time and pace',
    body: [
      'Every turn covers more time than the last. The first turn of the Dusk is 40 years; by its end a turn is about a trillion years. The Chronometer across the top shows where you are in the remaining life of the universe, with the milestones and your forecasts marked on it.',
      'Pace (bottom right) changes the length of the coming turns. Quick makes them shorter: more decisions while something bright is burning, but each turn collects less energy. Slow makes them longer: more energy per turn, but the universe moves on faster between decisions, and only minds that can slow their own clocks (Echoes, Coldminds) avoid paying for the extra time. Tide is the natural pace of the age. How far you can go either way grows with research (Hibernation Protocols slows, Quickening quickens); letting the Prophet of Stillness’s idea spread lets you slow one step further still. A pace that would change nothing at the moment is greyed out and says why: while a new star’s clock or a flare sets your turns, when a flare will cut the turn short whatever the pace, or beyond what the Dark Era’s calendar allows.',
      'Sleep makes the whole civilization dormant: upkeep falls to a tenth, energy still comes in, nothing is built or learned. Long Sleep (after Hibernation Protocols) ends several turns on its own and stops for any decision.',
      'Fleets fly below the speed of light, but because every turn is longer than the last, even a trip across the galaxy takes only a few turns once the turns are long.',
    ],
  },
  {
    id: 'm-energy',
    title: 'Energy',
    body: [
      'Energy is the master resource. The big number is your reserve; the small one beside it is what the next turn will add or cost. Hover over it for the breakdown by settlement.',
      'Income comes from collectors (solar arrays, orbital collectors, the Dyson swarm; later ember collectors, accretion engines, Penrose harvesters and Hawking collectors), from geothermal taps, fusion, and from each settlement’s Hearth, a small power core that runs on whatever is local (where nothing is left, on stored fuel and salvage: a little, and never nothing). Light collectors are named for what they actually gather where they stand: Solar Arrays at a living star, Glow Arrays at a white dwarf, Infrared Nets at a dead star (nothing once it has cooled, unless something warms it again), Beam Arrays at a pulsar, Disk Arrays at a black hole; each yields only what that source really gives, and the build list shows how much. Where a star has no light left to give, a light collector cannot be built, and one already there says it has nothing to gather. Geothermal taps (and a Hearth on a warm world) draw on the world’s core heat, which runs out after the Last Light: a fifth less each turn. The cold gives one thing back: under a dark sky Coldminds and Cold Vaults cost half their upkeep (thinking is cheaper in the cold). Surface arrays also get the light where their world is, by the inverse-square law: a world close to its star catches more (up to ×2.5), one far out much less (down to ×0.05); the homeworld’s orbit is the standard ×1, and each planet panel shows its Sunlight. Orbital collectors and Dyson swarms sit wherever the light is best, so their world does not matter.',
      'Upkeep comes from people (Kin are by far the most expensive), from some structures, and from research: while a project is running, the labs draw a little power. If the reserve empties, settlements start to starve: people die and resolve falls. If the reserve is full, extra energy is wasted; build Energy Vaults or spend it.',
      'When energy is short: pause research, sleep for a few turns, cool Echoes into Coldminds, or put Kin into cold sleep.',
    ],
  },
  {
    id: 'm-settlements',
    title: 'Settlements',
    body: [
      'Click a settlement (on the map, or in Systems on the rail) to open its panel. Overview shows its yields, people, world and structures. Build shows its queue and what it can build; Rush finishes the first item at once for matter and energy, and people resent it. Structures come grouped by what they are for, each kind with its own coloured icon: energy, storage, matter, industry, insight, accord, people (room for every kind of mind, cold sleep and the ways from one kind into another), the world itself, and defence. The buttons above the list show one kind at a time, and the choice stays as you move between settlements. A structure can be taken apart from Overview (the × on it): the matter it cost comes back (its energy, once matter is gone), and the work costs a fifth of what it took to build, in energy, at least 5; the work that built it is lost. Not while it houses people with nowhere else to live there, or while ships in the queue need the Shipyard. What a building does once, when it is finished (Volatile Shepherding’s water, a Core Stimulator’s heat, a new Confluence Node for the Chorus’s wish for one), it does only the first time at a settlement.',
      'Focus shifts a settlement’s effort toward energy, matter, industry, insight or accord: that one rises (by a quarter to two fifths) and energy, industry, insight and accord, where they are not the focus, fall by a tenth. Matter is touched only by its own focus. Instead of building, a settlement can work on something else: in its Build tab, under When nothing is queued, choose recycling (matter: matter is conserved, so what we have can be reused; once the protons are gone it yields a little energy instead), study (insight), tending its collectors and hearth (energy, at most a quarter more than they make) or morale (resolve). It works on that whenever its queue is empty; to switch to it now, remove what is queued (everything paid up front comes back). Each choice turns industry into about as much as the others, a tenth of what a building of that kind would make. A settlement with nothing queued and nothing chosen only recycles, and is called idle. Overdrive (after the Overdrive Protocols charter) runs the Hearth hot for much more energy, at a cost in damage and attention from the Hunger.',
      'People need room. A world’s natural room for Kin is about 12 × its habitability × its vitality, rounded down (a third of that on a rogue or feeding world), and each planet’s panel shows it as Room for Kin. So a world below about 8% (habitability × vitality) has none, and Kin can live there only in domes. Beyond that, Kin need housing: Habitat Domes hold 3 each (up to 5), Deep Warrens 4 (up to 3), Garden Arks 4. Kin never grow past their room, and if room shrinks below them (a world dying, the Last Light) the extra die, or go into cold sleep under the Cold Sleep Lottery. So you need domes on any world that is not alive, on a living world once you want more Kin than it holds, and everywhere once the living worlds freeze. Echoes live in Substrate Cores, Coldminds in Cold Vaults, the Lattice in Lattice Foundries. Housing costs upkeep only for the share that is lived in.',
      'The Deep is the orbital space around each star, listed with its worlds. It has no ground, water or rock, so its panel shows no habitability, room or matter, and nothing can be mined there. What it holds is orbit. Orbital Collectors and Orbital Foundries work there, and some structures exist only in the Deep: the Dyson Swarm, the Stellar Lifter, and later most ways of drawing power from dead stars, neutron stars and black holes. Any of your settlements in the system can build those from its own list, so you do not have to settle the Deep to use them. Minds on substrate live there as well as anywhere (a Seedcore settles it), and Kin can live there in Habitat Domes (in the Dusk only once you have Orbital Industry). A settlement in the Deep keeps a Hearth fed by starlight, without a planet’s core heat, and when a world falls into its dead star, its people escape to the Deep.',
      'Living worlds die. Aster is losing its magnetic field (a Magnetic Shield slows that), and a living world freezes once its own star has died and the last of its light has faded (even its warmest ground below 195 K), or at the Last Light, when the rest go out: within a few turns it becomes an ice world or bare rock, unless you keep it warm with Orbital Lamps or slow it with a Core Stimulator. Its panel says when it is cooling, and how many turns it has left once it freezes. Life under an ice shell, kept warm by tides, lasts until the Last Light.',
      'Conversions (in the People section): Upload turns a Kin into an Echo, Merge two Echoes into a Chorus, Cool an Echo into a Coldmind. Freeze and Thaw move Kin in and out of cold sleep. Echoes also form by themselves in free substrate (Substrate Cores), about one every five turns while your reserve stays above 15 energy; uploading is the fast way.',
    ],
  },
  {
    id: 'm-expand',
    title: 'Exploring and expanding',
    body: [
      'Stars you can see are on the map; their worlds are unknown until one of your ships surveys the system. Any ship charts every system it reaches or waits in; probes are simply the cheapest, see farthest and can explore by themselves. Select a probe (Fleets on the rail) and pick a destination from its Nearby list, or press Move and click a star. A survey charts every world and sometimes turns up something remarkable; a world at least 50% habitable is announced. Ships are eyes too: a ship sees the stars around wherever it is (a probe three times as far as a settlement), and a ship at the edge of the map (nothing uncharted it knows of within 2,000 light-years) takes a long look from each such system and picks out the nearest stars no one has seen (a probe three, any other ship one), even across the gulfs between clusters, so exploring can always go on. When a survey is complete (or a living world is found), the message about it has a Look button that takes you into that system (or to that world). The Ruins row of a world’s panel (Read again) and its find chips reopen the survey report, with what you chose. Systems (S) on the rail lists your settlements, and its second tab, Surveyed worlds (W), every charted world with its habitability, room for Kin, temperature and water. Switch that list to Systems for one line per star: its best world, its total room for Kin and what was found there. Sort it by what each kind of mind needs: Habitable and Room for Kin, Power for Echoes and the Chorus (the energy a settlement there could collect at the Tide with the collectors you can build now), Matter for the Lattice (what its mines, skimmers and lifters could raise), Lasting for Coldminds (how long before the world falls into its dead star). A settler ship’s Where to settle list ranks worlds the same way for the kind it carries.',
      'Settler ships, from any settlement with a Shipyard (the Expand section of the settlement panel, or Build then Ships):',
      'System Lighter: no research needed. Carries one family of Kin and a dome to another world of the same star. Its colonists come from the settlement that builds it.',
      'Seedcore (Mind Substrate): two Echoes and their substrate. Can settle almost anywhere, including the empty orbital space of a dead star.',
      'Kin Ark (Fusion Drives): two Kin and a dome, to any world except a gas giant. Lattice Spore (Autonomous Replicators) and Vault Ship (Cold Computation, Degenerate Age) carry Lattice and Coldminds.',
      'When a settler is ready, its panel lists where it can go (for Kin the most habitable worlds first, for other minds the nearest), with the natural room for Kin ("domes only" means nothing lives there) and the travel time. Launching costs energy; longer trips cost more.',
      'Trip times read like “~26t · 2.9 Myr”: turns at your current pace, then the cosmic time the flight takes. Ships never outrun light (a probe flies at 2% of it), but every turn is longer than the last, so a trip across the Coalescence needs far fewer turns than distance ÷ today’s turn length suggests. Quicken and the same flight takes more, shorter turns; slow down and it takes fewer. Choose on map (in a fleet’s panel or an idle ship’s card) sends a ship to any star you click; the banner shows the trip before you commit, and Esc cancels.',
      'Auto-explore (probes and other survey ships): the ship keeps charting on its own, always heading for the nearest star no one has surveyed and no other ship is bound for. It never takes the last of the reserve (it waits while launching would leave under 20 energy), stops asking for orders, and reports back when nothing is left to chart. Any order by hand, Hold, or Stop exploring ends it.',
      'When a ship runs out of orders, a card asks what next: the nearest unsurveyed stars (for a probe; other ships get the two nearest as well), or Fortify for warships. Fortified warships defend their system at double strength and turn raiders away from the capital; Hold parks any other ship. Neither is counted as idle again until you give it new orders.',
      'Collision stars (two brown dwarfs, each too small to burn hydrogen, collided and merged into a body heavy enough to burn it) are the brightest places of the Degenerate Age: while one burns on your map it heads every list of destinations, settlements and worlds, and its name shows on the galaxy map with a ✦. In this age the Systems window has a third tab, Collision stars, listing each one with the light it gives and the turns it has left at your pace. A turn here soon outlasts a collision star’s whole life (one to ten trillion years), and a helium star’s (two white dwarfs merged, a few hundred million years) many times over. So every new star lights as the turn it forms in ends (the game bends this: the two may have met at any moment of that turn), and its event lets you keep time with it, as with a flare: what is left of its life in six turns, whatever your pace, each lived in full and paying as one turn at the Tide, with the Pace panel counting them. That is free while your next turn is no more than a hundred times what is left of its life. Beyond that your minds must quicken to it, which costs 250 energy, once, for every further tenfold, though never more than a full store: a quicker pace pays less, a slower one more, and a White Fire costs everyone something, usually all the energy they hold. A star too brief for six turns (a helium giant’s 120,000 years, or late in the age a helium star) can still be caught in one, a flash, priced the same way: one turn that ends as it burns out (or, past about η 18, after the shortest turn the calendar can count, its light still lived in full). One clock at a time, but a new star that outlasts the one you keep time with can be followed on: its six turns begin as the first clock runs out, at the price it would cost from your own pace then and never less than 250 energy (a new star lights about as often as one goes out, so a clock passed on cheaply would hold the age still). The Pace panel names the star that waits. With Quickening, Quick ×10 works while you keep time too: each of the star’s turns splits into ten, each lived as a tenth of a Tide turn, so it gives the same light over ten times the turns, and every turn pays its upkeep. Whatever your pace you can study a new star instead, for insight and resolve, and in its light you find its worlds, so its system is charted. A helium star’s ultraviolet boils away the worlds closest to it (any whose warmest ground passes 3,000 K, and rubble from 1,600 K; gas and ice giants are spared) before the turn ends: its event names them, and our people there flee to the Deep, three in four of them. A heavier one swells into a helium giant some 25 times the Sun’s size and swallows whatever orbits inside it. Let one pass, and late in the age it comes and goes inside your next turn.',
      'Think ahead: after the Last Light the useful places are white dwarfs warmed by dark matter (for ember collectors) and black holes (for accretion and, later, Penrose and Hawking harvesting).',
    ],
  },
  {
    id: 'm-research',
    title: 'Research and Great Works',
    body: [
      'Research is organised by field and by age. Pick any project whose requirements you have; later ages’ projects open as you reach them. Some are marked speculative: the science behind them is uncertain.',
      'Insight that overflows a finished project, or comes from discoveries and relics, is stored and goes into whatever you choose next; if the store already covers a project, it is worked out the moment you choose it. With a great deal stored (more than the dearest open project would need), the scholars spend only the excess, filling in the cheapest open projects on their own, up to three a turn; they never take up the Hunger’s ways or a deliberate choice such as Halo Siphons. When a project finishes, a prompt suggests what to do next. You can also pause research: the labs stop drawing power, and half of each turn’s insight is kept for later.',
      'Great Works are the projects that can end the game in something other than silence. Each belongs to an age, needs a technology and a condition (for example, enough Echoes and Coldminds). Once begun, half of your insight goes into the Work.',
    ],
  },
  {
    id: 'm-society',
    title: 'Threads, resolve and Charters',
    body: [
      'Your civilization is made of Threads: Kin (biological people, including any other living species who join you), Echoes (uploaded minds), the Chorus (merged minds), the Lattice (self-maintaining machines that ask for nothing) and Coldminds (minds near absolute zero). Each has its own costs, output and clock.',
      'Every Thread but the Lattice has a standing and a demand, shown in the Threads screen. Meeting demands raises standing; ignoring them lowers it. Resolve is the will to go on: everything you produce scales with it, and if it stays at zero the civilization gives up. Dissent slows work, and a Thread with very low standing may fork away and leave.',
      'Charters are laws bought with accord. Every Thread approves or disapproves of each one. The book holds five (nine with the Assembly of Threads), and a law stays in force until you repeal it: a repeal costs as much accord as the law did, turns every Thread’s opinion of it around and reopens the argument (a little dissent). What a law did once stays done; a windfall does not come twice. Some are dark: they feed on the dead and the weak, they bring you closer to the Hunger, they take no room in the book, and they cannot be undone. Accord has other uses, in Threads: Rally (resolve +3), Calm (dissent −4) and Hear them (one Thread’s standing +5). Each can be used once a turn; its price doubles with every use and eases back over about ten turns, so a full purse lasts, but cannot be spent all at once.',
    ],
  },
  {
    id: 'm-minds',
    title: 'Other minds and the Hunger',
    body: [
      'Messages travel at the speed of light, so news from far away is old when it arrives. The Signals screen holds messages that need an answer, your fellow survivors, and any other minds you have found.',
      'You begin with two survey probes and one old escort, Vigil, parked over the homeworld (a Warden: it defends where it is and does not ask for orders). The first time one of your ships comes near a swarm of the Hunger, it may let the ship go, or part of it may come for the ship: a warship can destroy it there; anything else is mauled but gets away, and what came for it heads for your nearest settlement, where your defences and Vigil meet it.',
      'Other young civilizations live in other star clusters, never next door: typically tens of thousands of light-years away, the nearest in one of the clusters closest to yours. A living civilization is far louder than a star, so you hear one from twenty-five times as far as you can see stars, the moment one of your ships surveys its star, or anywhere once you research Deep Listening; from the Degenerate Age on you hear everyone still alive. First contact is its own moment (you decide whether to tell everyone), it is marked on the map, and their name stays there in their colour (◈).',
      'Survivors may ask for aid, offer trades or joint works, send refugees, or raid you. You can help them, take them in, or take their stars from them.',
      'You can ask them for help too (Signals, Ask for help). Your request and their answer travel at the speed of light, and so does the beam that carries what they give, so it comes back after the round trip: many turns early in the Dusk, almost at once in later ages. They decide by how they feel about you, how they are faring and what you have given them; giving costs them a little, a civilization that is failing has nothing to spare, and a hostile one refuses and, if you are weak, now knows it. Every request costs some goodwill (more if you keep asking), one at a time, at most once every 8 turns each.',
      'You can raid them too. Park a warship at one of their stars and Raid (click twice to confirm): every warship there joins in and takes part of their reserve and some matter, if it gets past their defences; if not, your ships are hurt. Either way they will not forgive it, every civilization you know hears of it, and your own people lose Resolve and gain Dissent. The same civilization can be raided at most once every five turns, and one you have raided may come back for what you took. Fortified warships or a Defense Grid over the capital turn their raiders away.',
      'Echoes live on substrate, never on the land. Every settler ship brings its people’s first home (a Seedcore unfolds into a Substrate Core), and uploads need free substrate. Echoes that reach you through an event with nowhere to run wait in the archive, costing nothing, and move in as soon as a core has room (the Threads screen shows how many are waiting).',
      'The Slow Ones think on clocks of millions of years; you can only talk to them when your own clock comes close to theirs. The Unlit answer moved masses with moved masses: read their pattern and answer it with a gesture.',
      'The Hunger is a mindless swarm of harvesters. Light and heat draw it. Defend with Defense Grids and warships, hide under the Blackout charter, lure it with decoy beacons, or learn the Command Language and tame it. Taking its ways as your own raises Taint. A feeding swarm eats its star’s worlds: every turn it takes some of their mineral richness and hydrogen, which never grow back, so mines and skimmers there yield less. It leaves rust: a stain on the worlds and a red ring on the map, marking how much it has fed there (the star’s panel shows it). Rust never fades, and does no harm by itself.',
      'Swarms catch ships. A ship that stops at a star where a swarm is feeding, with no settlement of yours there to fight beside it, is attacked more often than not, turn after turn while it stays: a warship may beat off a small swarm and salvage what it kills, but a probe rarely comes back from a grown one. A swarm asleep in the dark strikes less often, and you cannot see it coming. Swarms you can see are marked in a ship’s list of destinations, and exploring probes steer around them; under the Blackout charter your ships are noticed half as often.',
    ],
  },
  {
    id: 'm-crossings',
    title: 'Forecasts and Crossings',
    body: [
      'Forecasts (bottom left, and as pins on the Chronometer) warn you of what is coming and roughly when: stars changing, worlds falling into their dead stars, galactic evaporation, the embers fading, proton decay. Click one to find it on the map; close it with the ×. The turn count under each follows the pace you have chosen (hover for the figure at the Tide).',
      'A red dwarf does not swell into a giant. At the end of its life it shrinks and heats up into a blue dwarf, over a hundred times brighter, for a few billion years, then collapses into a white dwarf. Late in the Dusk that flare is shorter than a single turn, so when one of your stars begins it the turn stops there, whatever the pace (the Pace panel says so), and you decide; that short turn pays as one turn at the Tide at most. Its worlds get far too hot to live on, even on the night side: Kin need domes, cold berths or Night-side Shelters (dug when the flare begins, as many as your matter pays for; also buildable while it lasts), and every settlement loses one unsheltered Kin a turn while it burns. You can keep time with the flare, six turns lived in full (the flare sets their length, not your pace, and each pays as one turn at the Tide whatever pace you pick), with about three times the light for collectors there and six more turns to prepare for the Last Light; or let it pass within the next turn. The seas boil away either way. Farther out the same warmth can melt a frozen world with water into open ocean: a Thawed ocean (273 to 340 K) has room for 5 Kin by the water without domes for as long as the flare lasts, a refuge worth a Lighter trip; a Hot sea (340 K to boiling) is liquid but too hot to live by. Both freeze again when the star collapses, and whatever still lives on its worlds then freezes as the white dwarf fades, unless Orbital Lamps keep it warm.',
      'The Last Light (end of the Dusk): every star becomes a white dwarf. Prepare starless power (ember collectors, fusion, geothermal), fill your reserve, put Kin into cold sleep.',
      'The end of the Degenerate Age depends on what becomes of matter, which you may not know yet: the Proton Question tells you, and the neutron stars show it near η 30. Until then the Chronometer shows the stretch where the age might end as a hatched band, and every date that depends on it as a question.',
      'If protons decay: the Great Decay (η 39). Every planet and dead star dissolves. Only minds on Leptonic Substrate survive, and they move to the black holes. Research Leptonic Computation and build it in time; Penrose harvesters at black holes will keep you going afterwards.',
      'If matter is stable: the Last Warmth (η 30), when the neutron stars cool below the faint glow of the black holes. Nothing dissolves, but from then on only the black holes are sources.',
      'If space itself slowly unmakes matter (curvature radiation, a recent and unconfirmed theory): the Last Warmth comes when the neutron stars burst, near η 68, and settlements at one are lost. The dwarfs fade by η 85, their worlds drifting loose, and at the Great Evaporation (η 89.5) every world is gone, as at the Great Decay: build Leptonic Substrate in time, near a black hole that will outlast it. Curvature Collectors gather a neutron star’s faint glow until then.',
      'The Last Horizon (end of the Black Hole Age): the last great black holes evaporate. What is left is your reserve and your Continuity.',
    ],
  },
  {
    id: 'm-endings',
    title: 'Endings',
    body: [
      'Victories come from the Great Works: The Long Thought (Echoes and Coldminds), One Voice (the Chorus), The Quiet Lattice (the Lattice), The Aeon Seed (at the Heart, with the Slow Ones), The Last Garden (living Kin, if protons are stable).',
      'Recurrence: simply still exist when the calendar reaches 10^(10^122) years. The Hunger: become it.',
      'Defeat: Silence (no one left), The Will Fails (resolve at zero for too long), The Fade (Continuity lost in the Dark Era).',
    ],
  },
  {
    id: 'm-controls',
    title: 'Controls',
    body: [
      'Music follows the age and the moment. Under Playlist in Settings you choose what each age plays: its recordings, the game’s own synthesized score, or any mix of them, which take turns (a lone piece repeats); Canon first lets the Canon open the Degenerate Age, or not. To hear a particular age’s music now (the Canon on its own, say), pick it under Music track; Automatic hands it back to the age.',
      'Mouse: drag to turn the view, right-drag or two fingers to pan, wheel or pinch to zoom (around whatever the view is centred on, so it stays in the middle; once you pan away, toward whatever is under the pointer). Click to select. To look inside a star system: double-click it, tap it again on a touchscreen, press Look inside, or click it and zoom in; zoom out past the edge of a system to return to the galaxy. Click a planet to select it; double-click it (or tap it on a touchscreen) to fly there: it stays in focus as it orbits (you can still turn, pan and zoom around it) until you pick another world, double-click the star, or press the whole-system button. Every system and planet panel lists the system’s worlds: click one to go to it. Double-click a fleet (tap it twice) to follow it the same way, in the galaxy or inside a system; Centre in its panel keeps it in the middle of the view without zooming in. The fleet’s button under the map, or the lit Follow or Centre in its panel, lets go. On the map a thin pale ring marks a surveyed system, a green ring (and a green name) one with an unsettled living world, the pulsing ring your own settlements; names in dim italics are stars seen but not yet surveyed. An idle ship’s card names the system it waits in: click the name to centre the view there, or Look inside. Pause (or P) holds every world still in its orbit. Clicking a star on the galaxy map makes it the centre the view turns and zooms around; leaving a system brings you back centred on it, and a game always opens centred on your capital. The view button (or V) switches between Natural light, Enhanced (light amplification: dark worlds, night sides and dead stars show their surfaces, and the map keeps every known star visible) and Thermal (false colour by temperature, with a scale; settlements show as warm spots). It changes only what you see. In every light a world looks as warm as it is: open sea where its ground is above freezing, a veil of steam past boiling, a dull red glow past about 800 K, a crust cracked with lava past about 1,500 K; on a locked world the day side and the night side can differ.',
      'Saving: Save / load on the rail keeps as many named save slots as your browser will hold (load, overwrite or delete each), besides a quick save (Menu) and the autosave taken every turn. Export a file to keep a game safe or to carry it to another device.',
      'Keys: Enter ends the turn. R research, S systems, F fleets, T threads, C charters, G signals, L the Record, K the Codex, W surveyed worlds, H home, P pause or play the orbits, Esc closes a window or clears the selection.',
    ],
  },
];
